/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "beoyedtbzwspgpjwuzxf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlb3llZHRiendzcGdwand1enhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTcwNzEsImV4cCI6MjA3NTY3MzA3MX0.F2aROf8tvO0k0xvhZe-J7j6k-blnv2FojsKId1sP-EQ"